// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\Lab3_farrow_impl\Farrow_Canonic_tb.v
// Created: 2020-04-30 17:30:29
// 
// Generated by MATLAB 9.8 and HDL Coder 3.16
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.0001
// Target subsystem base rate: 0.0001
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0.0001
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Out1                          ce_out        0.0001
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Farrow_Canonic_tb
// Source Path: 
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Farrow_Canonic_tb;



  reg  clk;
  reg  reset;
  wire clk_enable;
  wire Out1_done;  // ufix1
  wire rdEnb;
  wire Out1_done_enb;  // ufix1
  reg [11:0] Out1_addr;  // ufix12
  wire Out1_active;  // ufix1
  reg [11:0] Quantization_out1_addr;  // ufix12
  wire [11:0] Gain_out1_addr_delay_1;  // ufix12
  reg  tb_enb_delay;
  reg signed [31:0] fp_In2;  // sfix32
  reg [11:0] rawData_In2;  // ufix12_En8
  reg signed [31:0] status_In2;  // sfix32
  reg [11:0] holdData_In2;  // ufix12_En8
  reg [11:0] In2_offset;  // ufix12_En8
  wire [11:0] In2;  // ufix12_En8
  wire Quantization_out1_active;  // ufix1
  wire Quantization_out1_enb;  // ufix1
  wire [11:0] Quantization_out1_addr_delay_1;  // ufix12
  reg signed [31:0] fp_In1;  // sfix32
  reg signed [15:0] rawData_In1;  // sfix16_En14
  reg signed [31:0] status_In1;  // sfix32
  reg signed [15:0] holdData_In1;  // sfix16_En14
  reg signed [15:0] In1_offset;  // sfix16_En14
  wire signed [15:0] In1;  // sfix16_En14
  reg  check1_done;  // ufix1
  wire snkDonen;
  wire resetn;
  wire tb_enb;
  wire ce_out;
  wire signed [15:0] Out1;  // sfix16_En14
  wire Out1_enb;  // ufix1
  wire Out1_lastAddr;  // ufix1
  wire [11:0] Out1_addr_delay_1;  // ufix12
  reg signed [31:0] fp_Out1_expected;  // sfix32
  reg signed [15:0] Out1_expected;  // sfix16_En14
  reg signed [31:0] status_Out1_expected;  // sfix32
  wire signed [15:0] Out1_ref;  // sfix16_En14
  reg  Out1_testFailure;  // ufix1
  wire testFailure;  // ufix1


  assign Out1_done_enb = Out1_done & rdEnb;



  assign Out1_active = Out1_addr != 12'b101110111000;



  assign #1 Gain_out1_addr_delay_1 = Quantization_out1_addr;

  // Data source for In2
  initial
    begin : In2_fileread
      fp_In2 = $fopen("In2.dat", "r");
      status_In2 = $rewind(fp_In2);
    end

  always @(Gain_out1_addr_delay_1, rdEnb, tb_enb_delay)
    begin
      if (tb_enb_delay == 0) begin
        rawData_In2 <= 12'bx;
      end
      else if (rdEnb == 1) begin
        status_In2 = $fscanf(fp_In2, "%h", rawData_In2);
      end
    end

  // holdData reg for Gain_out1
  always @(posedge clk or posedge reset)
    begin : stimuli_Gain_out1
      if (reset) begin
        holdData_In2 <= 12'bx;
      end
      else begin
        holdData_In2 <= rawData_In2;
      end
    end

  always @(rawData_In2 or rdEnb)
    begin : stimuli_Gain_out1_1
      if (rdEnb == 1'b0) begin
        In2_offset <= holdData_In2;
      end
      else begin
        In2_offset <= rawData_In2;
      end
    end

  assign #2 In2 = In2_offset;

  assign Quantization_out1_active = Quantization_out1_addr != 12'b101110111000;



  assign Quantization_out1_enb = Quantization_out1_active & (rdEnb & tb_enb_delay);



  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 3000
  always @(posedge clk or posedge reset)
    begin : Quantization_process
      if (reset == 1'b1) begin
        Quantization_out1_addr <= 12'b000000000000;
      end
      else begin
        if (Quantization_out1_enb) begin
          if (Quantization_out1_addr >= 12'b101110111000) begin
            Quantization_out1_addr <= 12'b000000000000;
          end
          else begin
            Quantization_out1_addr <= Quantization_out1_addr + 12'b000000000001;
          end
        end
      end
    end



  assign #1 Quantization_out1_addr_delay_1 = Quantization_out1_addr;

  // Data source for In1
  initial
    begin : In1_fileread
      fp_In1 = $fopen("In1.dat", "r");
      status_In1 = $rewind(fp_In1);
    end

  always @(Quantization_out1_addr_delay_1, rdEnb, tb_enb_delay)
    begin
      if (tb_enb_delay == 0) begin
        rawData_In1 <= 16'bx;
      end
      else if (rdEnb == 1) begin
        status_In1 = $fscanf(fp_In1, "%h", rawData_In1);
      end
    end

  // holdData reg for Quantization_out1
  always @(posedge clk or posedge reset)
    begin : stimuli_Quantization_out1
      if (reset) begin
        holdData_In1 <= 16'bx;
      end
      else begin
        holdData_In1 <= rawData_In1;
      end
    end

  always @(rawData_In1 or rdEnb)
    begin : stimuli_Quantization_out1_1
      if (rdEnb == 1'b0) begin
        In1_offset <= holdData_In1;
      end
      else begin
        In1_offset <= rawData_In1;
      end
    end

  assign #2 In1 = In1_offset;

  assign snkDonen =  ~ check1_done;



  assign resetn =  ~ reset;



  assign tb_enb = resetn & snkDonen;



  // Delay inside enable generation: register depth 1
  always @(posedge clk or posedge reset)
    begin : u_enable_delay
      if (reset) begin
        tb_enb_delay <= 0;
      end
      else begin
        tb_enb_delay <= tb_enb;
      end
    end

  assign rdEnb = (check1_done == 1'b0 ? tb_enb_delay :
              1'b0);



  assign #2 clk_enable = rdEnb;

  initial
    begin : reset_gen
      reset <= 1'b1;
      # (20);
      @ (posedge clk)
      # (2);
      reset <= 1'b0;
    end

  always 
    begin : clk_gen
      clk <= 1'b1;
      # (5);
      clk <= 1'b0;
      # (5);
      if (check1_done == 1'b1) begin
        clk <= 1'b1;
        # (5);
        clk <= 1'b0;
        # (5);
        $stop;
      end
    end

  Farrow_Canonic u_Farrow_Canonic (.clk(clk),
                                   .reset(reset),
                                   .clk_enable(clk_enable),
                                   .In1(In1),  // sfix16_En14
                                   .In2(In2),  // ufix12_En8
                                   .ce_out(ce_out),
                                   .Out1(Out1)  // sfix16_En14
                                   );

  assign Out1_enb = ce_out & Out1_active;



  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 3000
  always @(posedge clk or posedge reset)
    begin : c_2_process
      if (reset == 1'b1) begin
        Out1_addr <= 12'b000000000000;
      end
      else begin
        if (Out1_enb) begin
          if (Out1_addr >= 12'b101110111000) begin
            Out1_addr <= 12'b000000000000;
          end
          else begin
            Out1_addr <= Out1_addr + 12'b000000000001;
          end
        end
      end
    end



  assign Out1_lastAddr = Out1_addr >= 12'b101110111000;



  assign Out1_done = Out1_lastAddr & resetn;



  // Delay to allow last sim cycle to complete
  always @(posedge clk or posedge reset)
    begin : checkDone_1
      if (reset) begin
        check1_done <= 0;
      end
      else begin
        if (Out1_done_enb) begin
          check1_done <= Out1_done;
        end
      end
    end

  assign #1 Out1_addr_delay_1 = Out1_addr;

  // Data source for Out1_expected
  initial
    begin : Out1_expected_fileread
      fp_Out1_expected = $fopen("Out1_expected.dat", "r");
      status_Out1_expected = $rewind(fp_Out1_expected);
    end

  always @(Out1_addr_delay_1, ce_out, tb_enb_delay)
    begin
      if (tb_enb_delay == 0) begin
        Out1_expected <= 16'bx;
      end
      else if (ce_out == 1) begin
        status_Out1_expected = $fscanf(fp_Out1_expected, "%h", Out1_expected);
      end
    end

  assign Out1_ref = Out1_expected;

  always @(posedge clk or posedge reset)
    begin : Out1_checker
      if (reset == 1'b1) begin
        Out1_testFailure <= 1'b0;
      end
      else begin
        if (ce_out == 1'b1 && Out1 !== Out1_ref) begin
          Out1_testFailure <= 1'b1;
          $display("ERROR in Out1 at time %t : Expected '%h' Actual '%h'", $time, Out1_ref, Out1);
        end
      end
    end

  assign testFailure = Out1_testFailure;

  always @(posedge clk)
    begin : completed_msg
      if (check1_done == 1'b1) begin
        if (testFailure == 1'b0) begin
          $display("**************TEST COMPLETED (PASSED)**************");
        end
        else begin
          $display("**************TEST COMPLETED (FAILED)**************");
        end
      end
    end

endmodule  // Farrow_Canonic_tb

